[package]

name = "evict"
version = "0.1.0"
authors = ["Brandon Sanderson <bas.bsanders@gmail.com>"]

[[bin]]
name = "evict"
path = "src/evict/main.rs"
test = true

[dependencies]
genfsm = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
error-type = "*"
time = "*"

